version: "3"

output: prefixed

vars:
  BIN_DIR: bin

tasks:
  default:
    deps: [build]

  build:
    desc: Build all binaries
    deps: [build:bfsh, build:btsh, build:bfui]

  build:bfsh:
    desc: Build bfsh shell
    cmds:
      - go build -o {{.BIN_DIR}}/bfsh ./cmd/bfsh
    sources:
      - cmd/bfsh/*.go
      - rvfs/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/bfsh"

  build:btsh:
    desc: Build btsh shell (bubbletea)
    cmds:
      - go build -o {{.BIN_DIR}}/btsh ./cmd/btsh
    sources:
      - cmd/btsh/*.go
      - rvfs/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/btsh"

  build:bfui:
    desc: Build bfui TUI
    cmds:
      - go build -o {{.BIN_DIR}}/bfui ./cmd/bfui
    sources:
      - cmd/bfui/*.go
      - rvfs/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/bfui"

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  fmt:
    desc: Format all Go source files
    cmds:
      - gofmt -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Format and vet
    deps: [fmt, vet]

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  check:
    desc: Format, vet, and test
    cmds:
      - task: fmt
      - task: vet
      - task: test
